
# html lang
language: en

head:
  favicon: "/img/logo-64.jpg"
  high_res_favicon: "/img/logo.png"
  apple_touch_icon: "/img/logo.png"

header:
  info:
    - "Student of Computer Science"
    - "University of Vienna, Austria"
  slogan:
    - "Hello, nice to meet you!"
    - "I find web technologies fascinating and aspire to work as a full-stack developer in the future. Here you can find some projects that I've been working on."
  location: Vienna, Austria

img:
  logo: "/img/logo.png"
  avatar: "/img/avatar.png"

# main menu navigation
menu:
  Home:
    url: /
    icon: fa-home
  About Me: 
    url: /about 
    icon:

thumbnail:
  default: 'linear-gradient(120deg, rgba(41, 50, 60, 0.2), rgba(41, 50, 60, 0.1))'
sns:
  email:
    url: mailto:jgawrylkowicz@gmail.com
    icon: fa-envelope
    info: "jgawrylkowicz@gmail.com"
  facebook:
    url: https://www.facebook.com/facebook
    icon: fa-facebook
    info: "Jakub Gawrylkowicz"
  twitter:
    url: 
    icon: fa-twitter
    info:
  googleplus:
    url:
    icon: fa-googleplus
    info:
  github:
    url: https://github.com/jgawrylkowicz
    icon: fa-github
    info: "jgawrylkowicz"
  linkedin:
    url:
    icon: fa-linkedin
    info:
  telegram:
    url: 
    icon: fa-telegram
    info:

# Miscelaneous
favicon: /img/logo-128.png

# stylesheets loaded in the <head>
stylesheets:
- /css/sidebar.css
- /css/fontawesome.min.css

# scripts loaded in the end of the body
scripts:
- /js/jquery-3.3.1.min.js
- /js/jquery.pjax.js
- /js/sidebar.js
