
# html lang
language: en

head:
  favicon: "/img/logo-64.jpg"
  high_res_favicon: "/img/logo.png"
  apple_touch_icon: "/img/logo.png"

header:
  title: "Jakub<span>Gawrylkowicz</span>"
  info:
    - "Computer Science Student"
    - "University of Vienna, Austria"
  slogan:
    - "Hello, nice to meet you!"
    - "My name is Jakub Gawrylkowicz ... "
    - "... and I am currently living and studying in Vienna. I find web technologies fascinating and aspire to work as a full-stack developer in the future. "
  location: Vienna, Austria

img:
  logo: "/img/logo.png"
  avatar: "/img/avatar.png"

# main menu navigation
menu:
  Values:
    url: /
    icon: fa-home
    id: 'values'
  Projects:
    url: /
    icon: fa-home
    id: 'projects'
  About:
    url: /
    icon: fa-home
    id: 'projects'

    

thumbnail:
  default: 'white'
  automatic_background: false

sns:
  email:
    url: mailto:jgawrylkowicz@gmail.com
    icon: mail
    tooltip: 'Send me an email to jgawrylkowicz@gmail.com'
  facebook:
    url: 
    icon: logo-facebook
    tooltip: 
  googleplus:
    url:
    icon: fa-googleplus
    tooltip: 
  github:
    url: https://github.com/jgawrylkowicz
    icon: logo-github
    tooltip: 'Browse my github at https://github.com/jgawrylkowicz'
  linkedin:
    url:
    icon: fa-linkedin
    tooltip: 
  telegram:
    url: 
    icon: fa-telegram
    tooltip: 
  source code:
    url: https://github.com/jgawrylkowicz/section
    icon: code
    tooltip: 'See the source code at github'

# Miscelaneous
favicon: /img/logo-128.png

# stylesheets loaded in the <head>
stylesheets:
- /css/section.css
- /css/aos.css
- #/css/tingle.css

# scripts loaded in the end of the body
scripts:
- /js/src/anime.min.js
- /js/src/aos.js
- /js/src/tingle.min.js
- /js/config.min.js
- https://unpkg.com/ionicons@4.4.2/dist/ionicons.js



