
# html lang
language: en

head:
  favicon: "/img/logo-64.jpg"
  high_res_favicon: "/img/logo.png"
  apple_touch_icon: "/img/logo.png"

header:
  slogan:
    - "Hello, nice to meet you!"
    - "I am a computer science student at the University of Vienna. I find web technologies fascinating and aspire to work as a full-stack developer in the future. Here you can find some projects that I've been working on."
  location: Vienna, Austria

img:
  logo: "/img/logo.png"
  avatar: "/img/avatar.png"

# main menu navigation
menu:
  Home: /
  About: /about
  Contact: /contact

thumbnail:
  default: 'linear-gradient(120deg, rgba(41, 50, 60, 0.2), rgba(41, 50, 60, 0.1))'
sns:
  email:
    url: mailto:jgawrylkowicz@gmail.com
    icon: fa-envelope
  facebook:
    url: https://www.facebook.com/facebook
    icon: fa-facebook
  twitter:
    url: 
    icon: fa-twitter
  googleplus:
    url:
    icon: fa-googleplus
  github:
    url: https://github.com/jgawrylkowicz
    icon: fa-github
  linkedin:
    url:
    icon: fa-linkedin
  telegram:
    url: 
    icon: fa-telegram

# Miscelaneous
favicon: /img/logo-128.png

# stylesheets loaded in the <head>
stylesheets:
- /css/sidebar.css
- /css/fontawesome.min.css

# scripts loaded in the end of the body
scripts:
- /js/jquery-3.3.1.min.js
- /js/jquery.pjax.js
- /js/sidebar.js
