
# html lang
language: en

head:
  favicon: "/img/logo-64.jpg"
  high_res_favicon: "/img/logo.png"
  apple_touch_icon: "/img/logo.png"

header:
  title: "Jakub<span>Gawrylkowicz</span>"
  info:
    - "Computer Science Student"
    - "University of Vienna, Austria"
  slogan:
    - "Hello, nice to meet you!"
    - "My name is Jakub Gawrylkowicz ... "
    - "... and I am currently living and studying in Vienna. I find web technologies fascinating and aspire to work as a full-stack developer in the future. "
  location: Vienna, Austria

img:
  logo: "/img/logo.png"
  avatar: "/img/avatar.png"

# main menu navigation
menu:
  Home:
    url: /
    icon: fa-home
    id: 'home'
  Projects:
    url: /
    icon: fa-home
    id: 'projects'
  jgawrylkowicz@gmail.com:
    url: mailto:jgawrylkowicz@gmail.com
    icon:
    id: email
    

thumbnail:
  default: 'white'
  automatic_background: false

sns:
  email:
    url: mailto:jgawrylkowicz@gmail.com
    icon: fa-envelope
    info: "Send me an email"
  facebook:
    url: 
    icon: fa-facebook
    info: "Jakub Gawrylkowicz"
  twitter:
    url: 
    icon: fa-twitter
    info:
  googleplus:
    url:
    icon: fa-googleplus
    info:
  github:
    url: https://github.com/jgawrylkowicz
    icon: fa-github
    info: "See my other projects on Github"
  linkedin:
    url:
    icon: fa-linkedin
    info:
  telegram:
    url: 
    icon: fa-telegram
    info:
  source code:
    url: https://github.com/jgawrylkowicz/sidebar
    icon: fa-code
    info: "See the <code>source code</code>"

# Miscelaneous
favicon: /img/logo-128.png

# stylesheets loaded in the <head>
stylesheets:
- /css/section.css

# scripts loaded in the end of the body
scripts:
- /js/anime.min.js
- /js/barba.min.js
- /js/pace.min.js
- /js/config.min.js
#- /js/scroll-behavior.js



